Requires/Wants option in systemd unit file
pyslackers/ansible pull request #32
Opened 2017-07-06 13:38 UTC by ovv

2017-07-06 13:39 UTC, ovv commented
[Doc on systemd unit file](https://www.freedesktop.org/software/systemd/man/systemd.unit.html)

2017-07-06 17:29 UTC, mattrasband requested changes

2017-07-06 17:29 UTC, mrasband commented on roles/system_service/templates/etc/systemd/system/service.j2
> +{% if service_requires %}Requires={{ service_requires }}
Looks like you're missing the `{% endif %}` on both of these

2017-07-06 19:59 UTC, ovv commented on roles/system_service/templates/etc/systemd/system/service.j2
> +{% if service_requires %}Requires={{ service_requires }}
Oups

2017-07-12 08:37 UTC, ovv commented
@mrasband I think this is ok now ?

2017-07-12 12:16 UTC, mrasband commented
Yep, I think it's good

2017-07-12 13:24 UTC, merged