Dry up roles so we can describe a playbook in the sense of modeling a server
pyslackers/ansible pull request #9
Opened 2017-05-22 02:51 UTC by mrasband

I think this captures a more repeatable ansible structure, basically defining models in our playbooks rather than anticipating side effects of tasks.

This is not tested, it's meant as a starting talking point for discussion.

The short is things are dry'ed up a bit, roles are broken into things like `nginx` and `ssl`

2017-05-22 02:54 UTC, mrasband commented on roles/common/tasks/ssh.yml
> +  with_items:
Per the docs, there is this cool feature:

> The SSH public key(s), as a string or (since 1.9) url (https://github.com/username.keys)

2017-05-22 02:55 UTC, mrasband commented on roles/nginx/tasks/main.yml
> +- name: Disable default site
I added in disabling the default site, so the IP isn't really directly accessible

2017-05-22 02:55 UTC, mrasband commented on roles/pythondev-site/meta/meta.yml
> +  - { role: ssl, domain: {{ pythondev_domain }}, port: {{ pythondev_port }} }
I am not 100% sure this works as I have it, but it seems like it should - but they may need to be quoted.

2017-05-22 02:55 UTC, mrasband commented on roles/pythondev-site/tasks/main.yml
> -    - certbot
I moved `certbot` into an `ssl` role

2017-05-22 02:56 UTC, mrasband commented on roles/pythondev-site/tasks/main.yml
> +    home: /home/pythondev
The user module can do all this for us - no need to manually create homedirs

2017-05-22 02:56 UTC, mrasband commented on roles/ssl/templates/etc/nginx/sites-available/site-available.j2
> +server {
DRY'ed this piece, it takes args for the depenedency now.

2017-05-22 02:57 UTC, mrasband commented on roles/sysstat/tasks/common.yml
> +  with_items:
A lot of these should be in `common` probably - not sure what all goes where so wanted to ask.

Not sure why we need `libncurses` for a server

2017-05-22 17:26 UTC, ovv requested changes
Seems almost good to me. Be careful when rebasing master :)

2017-05-22 17:26 UTC, ovv commented on deploy.yml
> -      tags: pythondev-site
Why are we removing the tags ? 
It's a nice way to update only one prject without running all the playbook

2017-05-22 17:26 UTC, ovv commented on prepare_ubuntu16.04.yml
> +    - common
Why a separate playbook for the common role ? 

This playbook was used to install python2.7 on ubuntu server because it wasn't available

2017-05-22 17:26 UTC, ovv commented on roles/common/tasks/ssh.yml
> +    - https://github.com/Ovvovy.keys
I renamed myself to https://github.com/ovv :)

2017-05-22 17:26 UTC, ovv commented on roles/sysstat/tasks/common.yml
> +  with_items:
Not sure either. Maybe for certbot ?

Some are needed to build python I think. So we should move them in the python role.

2017-05-25 07:01 UTC, mrasband commented
Going to kill this for now and rework it a bit later

2017-05-25 07:01 UTC, closed without merging